### ISSUE TITLE
Switch_Active_Collection: Make a option to auto sync every time I select a object.

### ISSUE THREAD

**Issue by jiabaoyu** [EugeneDudavkin/small_addons#1]
Well done these scripts! 
I wish to sync the active collection automaticlly when I select any object. Thus, I don't have to move my cursor to the outliner to change the active collection before I want to add a object. Instead, I could just select something which belongs to the destination collection in the viewport.

**Comment by EugeneDudavkin** [comment]
Hello,
sorry for the late response.
Here is a version with what you suggested.
If it's active, it will always switch collection by active object and you can't click on different collection and change it until the icon not disabled (not active).
![switch_collection_by_active_object](https://user-images.githubusercontent.com/87300864/205037411-db38e80a-66e0-4f96-8dc4-d039a77a639b.png)

Check for the script **switch_collection_by_active_object.py** in my [small_addons](https://github.com/EugeneDudavkin/small_addons)

**Comment by jiabaoyu** [comment]
Works like a charm! Thanks for your work!
BTW, can't we register callbacks that listens to object selection event in BPY? Thus, if the user wants to manually make a collection active, he/she won't be interrupted by the script.

**Comment by EugeneDudavkin** [comment]
Unfortunately no (or maybe I did not quite understand what about).
This is how blender `handlers` works.
This addon is like a test, so I would not recommend to use it non stop, because when addon icon is active, it run checking script on every changes in blender. So it may cause FPS drop in large scene (need test).

I'm trying to figure it out how to run script only on mouse clicking on object.

Feel free to edit if you have any own ideas.

**Comment by jiabaoyu** [comment]
Thanks again! I just have some JavaScript knowledge. I'll learn some Python and BPY.

**Comment by EugeneDudavkin** [comment]
I think I made it possible. Try updated version.

**Comment by jiabaoyu** [comment]
Nope, it's basically the same behavior as the previous version.

**Comment by EugeneDudavkin** [comment]
Try to uninstall addon, then restart blender and install the new one.

Here's how it works now

https://user-images.githubusercontent.com/87300864/205098455-12411b80-856f-491c-8668-ec22b20dff37.mp4

**Comment by jiabaoyu** [comment]
It turns out that the last time I still get the 0.1.1 version maybe due to some cdn issue of github.
Now I've removed the old version and installed the 0.1.2, however it even just doesn't work.
I'm using 3.4 alpha of 26th Oct's build.

**Comment by EugeneDudavkin** [comment]
Interesting, I'll check 3.4

**Comment by jiabaoyu** [comment]
OK, I just did some research. I opened the console and saw a bunch of warnings and errors. Then I removed "M_tree (modular tree)", "import 3dm addon". I barely use those addons. Now your addon works!
There's one line of warning:
`fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\jiabaoyu\\OneDrive\\Portable\\blender addon\\addons\\fibonacci_heap_mod.py'`
I guess it doesn't have anything to do with your addon, right?

**Comment by jiabaoyu** [comment]
WOW, just found that when I kept the console in the background and select objects in the viewport, blender instantly freezes.
Then if I press "ctrl+c" in the console, blender goes back alive and interactive. P.S., this doesn't always happen, just found twice.

**Comment by EugeneDudavkin** [comment]
> I guess it doesn't have anything to do with your addon, right?

Right, it's a different one.

I guess I find what a problem. Trying to make it work. Some how it depend on other addon enabled :)

**Comment by jiabaoyu** [comment]
Great. But there're so many addons' out there. You could leave it as it is.

Edit: Never mind, found it.
<s>BTW I wonder which addon the fibonacci_heap_mod.py belong's to. <s>

**Comment by EugeneDudavkin** [comment]
Try again, I made update (version did not changed)

**Comment by jiabaoyu** [comment]
Just tried. What did you fixed? The last 0.1.2 version already works🤣

**Comment by EugeneDudavkin** [comment]
Just download a new one and replace it.
I missed one line and didn't want to change the version because of it. (without that line it can be unstable)

**Comment by jiabaoyu** [comment]
It works flawlessly. Thank you so much.
